const assert=require('node:assert/strict');
const A=require('../js/age-groups.js');
const config=require('../events_config.json');
const event=id=>[...config.past_events,...config.events].find(e=>e.id===id);
assert.deepEqual(A.describe('男30-39歲','2025_tpe','HM'),{sex:'男',min:30,max:39,source:null});
assert.equal(A.value(A.describe('女60歲+','2025_tpe','HM')),'age:女:60:plus');
assert.equal(A.describe('男甲組','2026_puma_night_run','EliteRun菁英半馬組'),null);
assert.equal(A.describe('女視障選手','2025_tpe','HM'),null);
assert.equal(A.describe('男子組','2025_tpe','HM'),null);
assert.equal(A.value(A.describe('男D組',event('2026_nat_geo_run'),'21K(半馬組)')),'age:男:30:39');
assert.equal(A.value(A.describe('男丁組',event('2025_uniform_invoice_run'),'半馬組(21km)')),'age:男:30:39');
assert.equal(A.value(A.describe('男子E組',event('2026_tainan_kutou'),'半程馬拉松21.0975km')),'age:男:30:39');
assert.equal(A.describe('女子G組',event('2026_tainan_kutou'),'半程馬拉松21.0975km'),null);
assert.equal(A.value(A.describe('男子H組',event('2026_tainan_kutou'),'路跑組10km')),'age:男:12:16');
assert.equal(A.value(A.describe('男丁組',event('2025_pocari_run'),'21K組')),'age:男:26:35');
assert.equal(A.value(A.describe('女高組',event('2025_pocari_run'),'21K組')),'age:女:66:plus');
assert.match(A.groupLabel({name:'男甲組',age:null}),/歲數定義待核實/);
const g=(min,max,sex='男')=>({name:`${min}-${max}`,age:{min,max,sex}});
assert.equal(A.match([g(60,69),g(70,null)],{min:60,max:null,sex:'男'}).length,2);
assert.equal(A.match([g(60,69),g(71,null)],{min:60,max:null,sex:'男'}).length,0);
assert.equal(A.match([g(36,50)],{min:40,max:49,sex:'男'}).length,0);
assert.equal(A.match([g(30,39,'女')],{min:30,max:39,sex:'男'}).length,0);
assert.equal(A.match([g(20,29),g(30,39)],{min:30,max:39,sex:'男'}).length,1);
console.log('Age checks passed: verified mappings, exact bands, complete adjacent unions, unknown and incompatible groups.');
